channels:
  - anaconda
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.9
  - pip=20.2.4
  - pip:
      - azureml-core==1.46.0
      - azureml-mlflow==1.46.0
      - azureml-pipeline-core==1.46.0
      - azureml-telemetry==1.46.0
      - azureml-interpret==1.46.0
      - azureml-responsibleai==1.46.0
      - azureml-automl-core==1.46.1
      - azureml-automl-runtime==1.46.1
      - azureml-train-automl-client==1.46.0
      - azureml-train-automl-runtime==1.46.1
      - azureml-dataset-runtime==1.46.0
      - azureml-defaults==1.46.0
      - inference-schema
  - numpy~=1.21.6
  - py-cpuinfo=5.0.0
  - mpi4py=3.1.3
  - click<8.0.0
  - pystan=2.19.1.1
  - boto3=1.15.18
  - botocore=1.18.18
  - joblib=0.14.1
  - cloudpickle=1.6.0
  - scikit-learn=0.22.1
  - pandas~=1.1.5
  - py-xgboost=1.3.3
  - fbprophet=0.7.1
  - holidays=0.10.3
  - setuptools-git
  - 'psutil>5.0.0,<6.0.0'
name: project_environment
